import type { KnowledgeGraph } from "./types";

export const seedGraph: KnowledgeGraph = {
  domains: [
    {
      id: "history",
      name: "History",
      description: "People, events, and ideas that shaped the world",
      icon: "scroll",
      color: "#d97706",
    },
    {
      id: "hard-sciences",
      name: "Hard Sciences",
      description: "Physics, engineering, and the material world",
      icon: "atom",
      color: "#2563eb",
    },
  ],
  categories: [
    {
      id: "revolutionary-war",
      domainId: "history",
      name: "Revolutionary War",
      description: "Founding era conflicts and key figures",
    },
    {
      id: "early-american-government",
      domainId: "history",
      name: "Early American Government",
      description: "Documents and institutions of the new republic",
    },
    {
      id: "american-presidents",
      domainId: "history",
      name: "American Presidents",
      description: "Leaders across eras — spot the gaps in your timeline",
    },
    {
      id: "wwii-cold-war",
      domainId: "history",
      name: "WWII & Cold War",
      description: "20th-century conflict and its aftermath",
    },
    {
      id: "semiconductors",
      domainId: "hard-sciences",
      name: "Semiconductors & Chip Design",
      description: "From silicon to systems-on-chip",
    },
    {
      id: "20th-century-physics",
      domainId: "hard-sciences",
      name: "20th Century Physics",
      description: "Breakthroughs that changed science and society",
    },
  ],
  nodes: [
    // Revolutionary War figures
    {
      id: "george-washington",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "George Washington",
      description: "Commander-in-Chief and first U.S. president",
      mastery: 2,
      notes: ["Watched a documentary on Valley Forge last weekend"],
      linkedNodeIds: ["american-presidents-overview", "battle-yorktown", "rev-war-battles"],
    },
    {
      id: "alexander-hamilton",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "Alexander Hamilton",
      description: "Aide-de-camp, Federalist architect, Treasury founder",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["early-american-government-overview"],
    },
    {
      id: "thomas-jefferson",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "Thomas Jefferson",
      description: "Author of the Declaration, third president",
      mastery: 2,
      notes: [],
      linkedNodeIds: ["declaration-of-independence", "american-presidents-overview"],
    },
    {
      id: "john-adams",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "John Adams",
      description: "Diplomat, second president, fierce advocate for independence",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["declaration-of-independence"],
    },
    {
      id: "rev-war-battles",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "Revolutionary Battles",
      description: "The major engagements — click in to subdivide the campaign map",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["george-washington"],
    },
    {
      id: "battle-saratoga",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "Battle of Saratoga",
      description: "Turning point that convinced France to join the war",
      mastery: 0,
      notes: [],
      linkedNodeIds: [],
      parentId: "rev-war-battles",
    },
    {
      id: "battle-yorktown",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "Battle of Yorktown",
      description: "Final major land battle; Cornwallis surrenders",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["george-washington"],
      parentId: "rev-war-battles",
    },
    {
      id: "battle-bunker-hill",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "Battle of Bunker Hill",
      description: "Early battle proving colonial resolve",
      mastery: 0,
      notes: [],
      linkedNodeIds: [],
      parentId: "rev-war-battles",
    },
    {
      id: "valley-forge",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "Valley Forge",
      description: "Winter encampment that forged the Continental Army",
      mastery: 2,
      notes: ["Watched a documentary on Valley Forge last weekend"],
      linkedNodeIds: [],
      parentId: "george-washington",
    },
    {
      id: "washington-presidency",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "Washington's Presidency",
      description: "Setting precedents for the executive branch",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["american-presidents-overview"],
      parentId: "george-washington",
    },
    {
      id: "farewell-address",
      domainId: "history",
      categoryId: "revolutionary-war",
      name: "Farewell Address",
      description: "Warnings against factions and foreign entanglements",
      mastery: 0,
      notes: [],
      linkedNodeIds: [],
      parentId: "george-washington",
    },
    // Early American government
    {
      id: "declaration-of-independence",
      domainId: "history",
      categoryId: "early-american-government",
      name: "Declaration of Independence",
      description: "1776 statement of colonial grievances and natural rights",
      mastery: 2,
      notes: [],
      linkedNodeIds: ["thomas-jefferson", "john-adams"],
    },
    {
      id: "articles-of-confederation",
      domainId: "history",
      categoryId: "early-american-government",
      name: "Articles of Confederation",
      description: "First constitution — weak central government",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["early-american-government-overview"],
    },
    {
      id: "early-american-government-overview",
      domainId: "history",
      categoryId: "early-american-government",
      name: "Constitutional Convention",
      description: "Philadelphia 1787 — designing the federal system",
      mastery: 0,
      notes: [],
      linkedNodeIds: ["alexander-hamilton", "articles-of-confederation"],
    },
    // Presidents — with intentional gap in Gilded/Progressive era
    {
      id: "american-presidents-overview",
      domainId: "history",
      categoryId: "american-presidents",
      name: "Presidential Timeline",
      description: "Meta-node tracking coverage across eras",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["george-washington", "presidents-1880-1940"],
    },
    {
      id: "presidents-revolutionary-era",
      domainId: "history",
      categoryId: "american-presidents",
      name: "Founding Presidents (1789–1825)",
      description: "Washington through Monroe",
      mastery: 2,
      notes: [],
      linkedNodeIds: ["george-washington", "thomas-jefferson", "john-adams"],
    },
    {
      id: "presidents-1880-1940",
      domainId: "history",
      categoryId: "american-presidents",
      name: "Presidents 1880–1940",
      description: "Gilded Age through WWII — a common gap",
      mastery: 0,
      notes: [],
      linkedNodeIds: ["presidents-revolutionary-era"],
    },
    {
      id: "presidents-modern",
      domainId: "history",
      categoryId: "american-presidents",
      name: "Modern Presidents (1945–present)",
      description: "Cold War through contemporary era",
      mastery: 1,
      notes: [],
      linkedNodeIds: [],
    },
    // WWII & Cold War
    {
      id: "manhattan-project",
      domainId: "history",
      categoryId: "wwii-cold-war",
      name: "Manhattan Project",
      description: "WWII atomic bomb program — bridge to physics",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["oppenheimer", "feynman", "wwii-overview", "nuclear-physics"],
    },
    {
      id: "los-alamos",
      domainId: "history",
      categoryId: "wwii-cold-war",
      name: "Los Alamos",
      description: "Secret lab where the bomb was designed",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["oppenheimer"],
      parentId: "manhattan-project",
    },
    {
      id: "trinity-test",
      domainId: "history",
      categoryId: "wwii-cold-war",
      name: "Trinity Test",
      description: "First nuclear detonation, July 1945",
      mastery: 0,
      notes: [],
      linkedNodeIds: ["nuclear-physics"],
      parentId: "manhattan-project",
    },
    {
      id: "uranium-enrichment",
      domainId: "history",
      categoryId: "wwii-cold-war",
      name: "Uranium Enrichment",
      description: "Oak Ridge and the industrial scale of the project",
      mastery: 0,
      notes: [],
      linkedNodeIds: [],
      parentId: "manhattan-project",
    },
    {
      id: "wwii-overview",
      domainId: "history",
      categoryId: "wwii-cold-war",
      name: "World War II",
      description: "Global conflict 1939–1945",
      mastery: 2,
      notes: [],
      linkedNodeIds: ["manhattan-project", "presidents-modern"],
    },
    {
      id: "cold-war-overview",
      domainId: "history",
      categoryId: "wwii-cold-war",
      name: "Cold War",
      description: "US–Soviet rivalry and nuclear deterrence",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["manhattan-project", "nuclear-physics"],
    },
    // Semiconductors
    {
      id: "photonics",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "Photonics",
      description: "Light-based communication and sensing in chips",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["lithography"],
    },
    {
      id: "lithography",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "Lithography",
      description: "Patterning circuits at nanometer scale",
      mastery: 2,
      notes: ["Researched EUV vs DUV last week"],
      linkedNodeIds: ["photonics", "gpu-design"],
    },
    {
      id: "packaging",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "Advanced Packaging",
      description: "Chiplets, interposers, and 3D stacking",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["substrates", "gpu-design"],
    },
    {
      id: "euv-lithography",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "EUV Lithography",
      description: "~13.5 nm light for leading-edge patterning",
      mastery: 2,
      notes: ["Researched EUV vs DUV last week"],
      linkedNodeIds: [],
      parentId: "lithography",
    },
    {
      id: "duv-lithography",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "DUV Lithography",
      description: "193 nm immersion still used for many layers",
      mastery: 1,
      notes: [],
      linkedNodeIds: [],
      parentId: "lithography",
    },
    {
      id: "photoresist",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "Photoresist",
      description: "Light-sensitive films that define the pattern",
      mastery: 0,
      notes: [],
      linkedNodeIds: [],
      parentId: "lithography",
    },
    {
      id: "chiplets",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "Chiplets",
      description: "Disaggregated die stitched into one package",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["gpu-design"],
      parentId: "packaging",
    },
    {
      id: "gpu-design",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "GPU Architecture",
      description: "Parallel compute units, memory hierarchy, tensor cores",
      mastery: 2,
      notes: [],
      linkedNodeIds: ["lithography", "packaging"],
    },
    {
      id: "substrates",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "Substrates",
      description: "Foundation materials connecting die to package",
      mastery: 0,
      notes: [],
      linkedNodeIds: ["packaging", "lithography", "gpu-design"],
      parentId: "packaging",
    },
    {
      id: "transistor-fundamentals",
      domainId: "hard-sciences",
      categoryId: "semiconductors",
      name: "Transistor Fundamentals",
      description: "MOSFETs, scaling, and Moore's Law limits",
      mastery: 2,
      notes: [],
      linkedNodeIds: ["lithography"],
    },
    // 20th century physics
    {
      id: "oppenheimer",
      domainId: "hard-sciences",
      categoryId: "20th-century-physics",
      name: "J. Robert Oppenheimer",
      description: "Theoretical physicist, Manhattan Project director",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["manhattan-project", "nuclear-physics"],
    },
    {
      id: "feynman",
      domainId: "hard-sciences",
      categoryId: "20th-century-physics",
      name: "Richard Feynman",
      description: "QED pioneer, Los Alamos contributor, legendary explainer",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["manhattan-project", "quantum-mechanics"],
    },
    {
      id: "nuclear-physics",
      domainId: "hard-sciences",
      categoryId: "20th-century-physics",
      name: "Nuclear Physics",
      description: "Fission, fusion, and chain reactions",
      mastery: 1,
      notes: [],
      linkedNodeIds: ["manhattan-project", "cold-war-overview"],
    },
    {
      id: "quantum-mechanics",
      domainId: "hard-sciences",
      categoryId: "20th-century-physics",
      name: "Quantum Mechanics",
      description: "Wave functions, uncertainty, and modern physics foundation",
      mastery: 0,
      notes: [],
      linkedNodeIds: ["feynman", "transistor-fundamentals"],
    },
  ],
  learningEntries: [
    {
      id: "learn-1",
      timestamp: "2026-09-01T14:00:00.000Z",
      title: "Revolutionary War documentary",
      content:
        "Watched a doc on Valley Forge and Washington's leadership. Learned about Yorktown as the decisive battle and Hamilton's role as aide-de-camp.",
      nodeIds: ["george-washington", "battle-yorktown", "alexander-hamilton"],
    },
    {
      id: "learn-2",
      timestamp: "2026-09-04T20:30:00.000Z",
      title: "Semiconductor deep dive",
      content:
        "Read about EUV lithography and how chip packaging is becoming as important as transistor scaling. Still unclear on substrate materials.",
      nodeIds: ["lithography", "packaging", "gpu-design"],
    },
  ],
  quizQuestions: [
    {
      id: "q-washington-1",
      nodeId: "george-washington",
      question: "Which battle is considered the final major land battle of the Revolutionary War?",
      options: ["Saratoga", "Bunker Hill", "Yorktown", "Lexington"],
      correctIndex: 2,
      explanation: "Cornwallis surrendered at Yorktown in 1781, effectively ending major combat.",
    },
    {
      id: "q-jefferson-1",
      nodeId: "thomas-jefferson",
      question: "Thomas Jefferson is primarily credited with drafting which document?",
      options: [
        "Articles of Confederation",
        "Declaration of Independence",
        "Federalist Papers",
        "Bill of Rights",
      ],
      correctIndex: 1,
      explanation: "Jefferson was the principal author of the Declaration of Independence (1776).",
    },
    {
      id: "q-lithography-1",
      nodeId: "lithography",
      question: "EUV lithography uses light at approximately which wavelength?",
      options: ["193 nm", "13.5 nm", "450 nm", "1 nm"],
      correctIndex: 1,
      explanation: "Extreme ultraviolet (EUV) lithography uses ~13.5 nm wavelength light.",
    },
    {
      id: "q-manhattan-1",
      nodeId: "manhattan-project",
      question: "The Manhattan Project was primarily motivated by fears that which country would develop atomic weapons first?",
      options: ["Japan", "Germany", "Soviet Union", "Italy"],
      correctIndex: 1,
      explanation: "Allied scientists feared Nazi Germany might achieve a nuclear weapon during WWII.",
    },
    {
      id: "q-substrates-1",
      nodeId: "substrates",
      question: "In advanced packaging, a substrate primarily serves to:",
      options: [
        "Generate EUV light",
        "Connect the silicon die to the package and PCB",
        "Replace the CPU cache",
        "Cool the GPU with liquid metal",
      ],
      correctIndex: 1,
      explanation: "Substrates provide mechanical support and electrical routing between die and board.",
    },
    {
      id: "q-hamilton-1",
      nodeId: "alexander-hamilton",
      question: "Alexander Hamilton founded which institution?",
      options: [
        "The Library of Congress",
        "The U.S. Treasury",
        "The Supreme Court",
        "West Point",
      ],
      correctIndex: 1,
      explanation: "Hamilton was the first Secretary of the Treasury and architect of early U.S. finance.",
    },
    {
      id: "q-feynman-1",
      nodeId: "feynman",
      question: "Richard Feynman won the Nobel Prize for work in:",
      options: [
        "General relativity",
        "Quantum electrodynamics (QED)",
        "String theory",
        "Thermodynamics",
      ],
      correctIndex: 1,
      explanation: "Feynman shared the 1965 Nobel for QED alongside Schwinger and Tomonaga.",
    },
    {
      id: "q-articles-1",
      nodeId: "articles-of-confederation",
      question: "The Articles of Confederation were replaced because they:",
      options: [
        "Granted too much power to the president",
        "Created a weak central government",
        "Banned slavery immediately",
        "Established a standing army",
      ],
      correctIndex: 1,
      explanation: "The Articles left the federal government too weak to tax or regulate commerce effectively.",
    },
  ],
};
